project_name: auth-proxy
before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/auth-proxy/main.go
    id: auth-proxy
    binary: auth-proxy
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-extldflags "-static" -X main.version={{ .Version }} -X main.commit={{ .Branch }}@{{ .ShortCommit }} -X main.buildTime={{ .Date }} -X main.builtBy=CI'
docker_manifests:
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-386"
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-armv7"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-arm64v8"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-386"
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-armv7"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-arm64v8"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-386"
dockers:
  - image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-amd64"
    ids: [auth-proxy]
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Authentication proxy
      - --label=org.opencontainers.image.source=https://github.com/habakke/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - ./static/ninja-portrait.svg
      - ./static/Inter-SemiBold.woff2
      - ./static/Inter-Regular.woff2
      - ./static/Inter-Medium.woff2
      - ./static/Inter-Bold.woff2
      - ./static/favicon.png
      - ./static/fa-solid-900.woff2
      - ./static/fa-regular-400.woff2
      - ./static/application.css
      - ./static/apple-touch-icon.png
      - ./templates/login.tpl
      - ./templates/error.tpl
      - ./templates/reset.tpl
      - ./templates/signup.tpl
  - image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-386"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-386"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-386"
    ids: [auth-proxy]
    goos: linux
    goarch: 386
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/386
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Authentication proxy
      - --label=org.opencontainers.image.source=https://github.com/habakke/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - ./static/ninja-portrait.svg
      - ./static/Inter-SemiBold.woff2
      - ./static/Inter-Regular.woff2
      - ./static/Inter-Medium.woff2
      - ./static/Inter-Bold.woff2
      - ./static/favicon.png
      - ./static/fa-solid-900.woff2
      - ./static/fa-regular-400.woff2
      - ./static/application.css
      - ./static/apple-touch-icon.png
      - ./templates/login.tpl
      - ./templates/error.tpl
      - ./templates/reset.tpl
      - ./templates/signup.tpl
  - image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-arm64v8"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-arm64v8"
    ids: [auth-proxy]
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Authentication proxy
      - --label=org.opencontainers.image.source=https://github.com/habakke/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - ./static/ninja-portrait.svg
      - ./static/Inter-SemiBold.woff2
      - ./static/Inter-Regular.woff2
      - ./static/Inter-Medium.woff2
      - ./static/Inter-Bold.woff2
      - ./static/favicon.png
      - ./static/fa-solid-900.woff2
      - ./static/fa-regular-400.woff2
      - ./static/application.css
      - ./static/apple-touch-icon.png
      - ./templates/login.tpl
      - ./templates/error.tpl
      - ./templates/reset.tpl
      - ./templates/signup.tpl
  - image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-armv7"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-armv7"
    ids: [auth-proxy]
    goos: linux
    goarch: arm
    goarm: 7
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Authentication proxy
      - --label=org.opencontainers.image.source=https://github.com/habakke/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - ./static/ninja-portrait.svg
      - ./static/Inter-SemiBold.woff2
      - ./static/Inter-Regular.woff2
      - ./static/Inter-Medium.woff2
      - ./static/Inter-Bold.woff2
      - ./static/favicon.png
      - ./static/fa-solid-900.woff2
      - ./static/fa-regular-400.woff2
      - ./static/application.css
      - ./static/apple-touch-icon.png
      - ./templates/login.tpl
      - ./templates/error.tpl
      - ./templates/reset.tpl
      - ./templates/signup.tpl
release:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
