apiVersion: v1
kind: Service
metadata:
  name: auth-proxy
  labels:
    app: auth-proxy
spec:
  selector:
    app: auth-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP