kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auth-proxy
  template:
    metadata:
      labels:
        app: auth-proxy
    spec:
      automountServiceAccountToken: true
      containers:
        - name: auth-proxy
          image: ghcr.io/habakke/auth-proxy:0.9.15
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: 8080
            - name: LOGLEVEL
              value: "debug"
            - name: ENV
              value: "local"
            - name: TARGET
              value: "http://<service>.<namespace>.svc.cluster.local"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: token
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: cookie-key
            - name: COOKIE_SEED
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: cookie-seed
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: google-oauth-client-id
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: google-oauth-client-secret
            - name: GOOGLE_OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: auth-proxy
                  key: google-oauth-callback-url
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 30
            httpGet:
              scheme: "HTTP"
              path: "/healthz"
              port : 80
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
